"""empty message

Revision ID: 9a2df6b762b1
Revises: 9f275f0a1ddf
Create Date: 2025-08-28 11:57:18.964672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2df6b762b1'
down_revision = '9f275f0a1ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('morning_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('morning_time')

    # ### end Alembic commands ###
