"""empty message

Revision ID: 9f275f0a1ddf
Revises: c0243fa44b0a
Create Date: 2025-08-26 11:28:34.806023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f275f0a1ddf'
down_revision = 'c0243fa44b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.drop_column('mail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mail', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
