"""empty message

Revision ID: c0243fa44b0a
Revises: d49590fcffaf
Create Date: 2025-08-26 11:00:37.843157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0243fa44b0a'
down_revision = 'd49590fcffaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slack_url', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mail', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mail')
        batch_op.drop_column('slack_url')

    # ### end Alembic commands ###
